table Orders
	lineageTag: 5b6caf62-1397-44e3-9c4d-1b30f7fddf1f

	measure 'Total Sales' = sum(Orders[Sales])
		lineageTag: 5675890e-8528-4e85-829b-5e32938add08

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = SUM(Orders[Profit])
		lineageTag: 19b20940-b869-40a4-8f04-047253c672ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 86bcb689-6bfb-4dba-a831-511070ec4cde
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 3059a869-cae5-4309-ac91-af5dae0c7baa
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bf137765-a7b6-49e4-9a3b-2a0731cbc339
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 7a8eb621-7002-478d-a13f-dc3c5ea23bde
			defaultHierarchy: LocalDateTable_9e8ce88a-9935-4b31-8556-9106e7e60f77.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a6104fb2-4448-4f19-aa08-961ad1dde046
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: d13a96e8-9335-4469-b431-6f34a478ec3f
			defaultHierarchy: LocalDateTable_707b07cf-958a-48e1-8b33-86844bcbeccc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: de015311-63a1-499f-b6b8-3d8b17445d70
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 61ae5fe4-0f12-4a6b-a3c4-d4c3618510fd
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 83b6606d-18e4-4e52-b6dc-860686e5ab27
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 7fec8c46-fb3e-4633-a8a2-e7a04bf4d290
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: 03b7f35b-2763-40de-bdfa-62d2e930de5e
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 1fb67ac0-ae71-402a-8014-e9f9b2568912
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State/Province
		dataType: string
		lineageTag: 8f014bc1-8b86-4bd3-aa82-0b2d6f545c2c
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: a61d1432-e6a7-4c65-a4a0-726433ddae08
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: d2f48256-e940-46b5-a33a-861f36aa2436
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: c93af004-4bf8-4f26-96f1-81b4fd20bedd
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: c917cbfc-5763-4514-ae4c-a1ce773fcc1b
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: e3766cc6-df6e-4130-8266-780d216c2290
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 74f580d5-b7d8-4e45-99d9-a1f0e1c3b048
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: d3b08527-4c80-4169-a808-6c96f92bb7e5
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 14e07c3b-ea9e-4ab5-a830-c434f264fa49
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: cfd194ab-3267-4f91-82be-12204fa2c2b0
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: a42bbc85-6395-4b57-b083-34b05c8c1833
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Docker\Documents\Sample Superstore\sample_superstore.xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

